<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\Ecommerce.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Ecommerce.Catalog.csproj" />
    <ProjectReference Include="..\Modules\Loyalty\Ecommerce.Loyalty.csproj" />
    <ProjectReference Include="..\Modules\Notifications\Ecommerce.Notifications.csproj" />
    <ProjectReference Include="..\Modules\Orders\Ecommerce.Orders.csproj" />
    <ProjectReference Include="..\Modules\Promotions\Ecommerce.Promotions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
