// <auto-generated />
using System;
using Ecommerce.Loyalty.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Loyalty.Infrastructure.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    [Migration("20260403023919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("loyalty")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Loyalty.Domain.LoyaltyAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CurrentTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_tier_id");

                    b.Property<int>("PointsBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("points_balance");

                    b.Property<int>("PointsLifetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("points_lifetime");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<DateTime?>("TierUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tier_updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_accounts");

                    b.HasIndex("CurrentTierId")
                        .HasDatabaseName("ix_loyalty_accounts_current_tier_id");

                    b.HasIndex("UserId", "ProgramId")
                        .IsUnique()
                        .HasDatabaseName("ix_loyalty_accounts_user_id_program_id");

                    b.ToTable("loyalty_accounts", "loyalty");
                });

            modelBuilder.Entity("Ecommerce.Loyalty.Domain.LoyaltyProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("EuroPerPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,6)")
                        .HasDefaultValue(0.01m)
                        .HasColumnName("euro_per_point");

                    b.Property<int?>("ExpiryDays")
                        .HasColumnType("integer")
                        .HasColumnName("expiry_days");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("PointsPerEuro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,4)")
                        .HasDefaultValue(10m)
                        .HasColumnName("points_per_euro");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_programs");

                    b.ToTable("loyalty_programs", "loyalty");
                });

            modelBuilder.Entity("Ecommerce.Loyalty.Domain.LoyaltyRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("integer")
                        .HasColumnName("points_spent");

                    b.Property<DateTime>("RedeemedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_redemptions");

                    b.ToTable("loyalty_redemptions", "loyalty");
                });

            modelBuilder.Entity("Ecommerce.Loyalty.Domain.LoyaltyReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("discount_value");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PointsCost")
                        .HasColumnType("integer")
                        .HasColumnName("points_cost");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward_type");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_rewards");

                    b.ToTable("loyalty_rewards", "loyalty");
                });

            modelBuilder.Entity("Ecommerce.Loyalty.Domain.LoyaltyTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BonusMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("bonus_multiplier");

                    b.Property<int>("MinPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("min_points");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Perks")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("perks")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("rank");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_tiers");

                    b.HasIndex("ProgramId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_loyalty_tiers_program_id_name");

                    b.HasIndex("ProgramId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ix_loyalty_tiers_program_id_rank");

                    b.ToTable("loyalty_tiers", "loyalty");
                });

            modelBuilder.Entity("Ecommerce.Loyalty.Domain.LoyaltyTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid?>("RewardId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_transactions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_loyalty_transactions_account_id");

                    b.ToTable("loyalty_transactions", "loyalty");
                });

            modelBuilder.Entity("Ecommerce.Loyalty.Domain.LoyaltyAccount", b =>
                {
                    b.HasOne("Ecommerce.Loyalty.Domain.LoyaltyTier", "CurrentTier")
                        .WithMany()
                        .HasForeignKey("CurrentTierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_loyalty_accounts_loyalty_tiers_current_tier_id");

                    b.Navigation("CurrentTier");
                });

            modelBuilder.Entity("Ecommerce.Loyalty.Domain.LoyaltyTransaction", b =>
                {
                    b.HasOne("Ecommerce.Loyalty.Domain.LoyaltyAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loyalty_transactions_loyalty_accounts_account_id");
                });

            modelBuilder.Entity("Ecommerce.Loyalty.Domain.LoyaltyAccount", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
